#include <string>
// Prints the Svaresa/Svaramanas rule matrix as Markdown, straight from the registry.
// Usage: eqcore_policy_doc > docs/audio-quality/POLICY_RULES.md
#include <cstdio>

#include "eqcore/policy.h"

using namespace eqcore::policy;

static const char* ownerText(Owner o) { return o == Owner::Fast ? "Svaresa fast (~250 ms, PCM)" : o == Owner::Slow ? "Svaramanas slow (~3 s, PCM)" : "Svaresa context (no PCM)"; }

int main() {
  std::printf("# Svaresa / Svaramanas rule matrix\n\n");
  std::printf("Generated by `eqcore_policy_doc` from `core/src/policy.cpp`; do not edit by hand. "
              "`validateRegistry()` and the evidence-gate tests check these rules; each row names a counterexample test "
              "(`policy_registry_is_consistent_and_every_rule_names_a_real_counterexample_test` verifies the test exists).\n\n");
  std::printf("Evidence gate (`admit`): every input must be present, valid, finite, at least the rule's confidence, no older than the "
              "rule's maximum age and (when required) from the current capture/route/format/parameter epoch. PCM metrics need the native "
              "engine; proxies (volume, route, clock) are only readable by rules that declare it and carry a hard cap. "
              "Otherwise the rule is skipped with a stated reason.\n\n");
  std::printf("| Rule | v | Owner | Inputs (units) | Min conf | Max age | Epoch | Native only | Action (bound) | Competes with | Reason | Rollback | Counterexample |\n");
  std::printf("|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
  for (const auto& r : rules()) {
    std::string in;
    for (int i = 0; i < r.inputCount; ++i) {
      const auto& s = spec(r.inputs[static_cast<size_t>(i)]);
      in += std::string(i ? "; " : "") + s.name + " [" + s.units + "]" + (s.proxy ? " (proxy)" : "");
    }
    if (in.empty()) in = "none (ownership/static)";
    std::printf("| %s | %d | %s | %s | %.2f | %s | %s | %s | %s %s [%g, %g] | %s | %s | %s | `%s` |\n", r.id, r.version, ownerText(r.owner),
                in.c_str(), r.minConfidence, r.inputCount ? (std::to_string(static_cast<int>(r.maxAgeSeconds)) + " s").c_str() : "-", r.sameEpoch ? "same" : "-",
                r.nativePcmOnly ? "yes" : "no", r.parameter, r.units, r.minAction, r.maxAction, r.competes, r.reason, r.rollback, r.counterexample);
  }
  std::printf("\n## Unmodelled loudness effects\n\n"
              "`predictedGuideLoudnessDeltaDb` models static EQ and the stereo guide. Bass Resolve (dynamic, capped at 1.5/0.75 dB), bass unmasking "
              "(<= 2 dB, only while cutting) and the spatial residual (<= 4 dB, band-limited, signal-dependent) are not predicted statically; "
              "they are covered by rendering the live implementation in the loudness-matched blind comparison.\n");
  return 0;
}
