"""Generates the Svan launcher mark (android/app/src/main/res/drawable/ic_launcher_foreground.xml):
a modern श (sha, as in श्रेष्ठम्) in molten-gold gradient with a continuous brass
shirorekha, inside the brass yantra ring with nine radial marks.

Glyph outline: Mukta Bold (SIL Open Font License 1.1, Ek Type), from
https://github.com/google/fonts/tree/main/ofl/mukta — the OFL permits using
glyph outlines in a logo. Usage:
    curl -LO https://raw.githubusercontent.com/google/fonts/main/ofl/mukta/Mukta-Bold.ttf
    python3 tools/brand/make_icon.py Mukta-Bold.ttf > android/app/src/main/res/drawable/ic_launcher_foreground.xml
"""
import sys
import mkmark

GLYPH_HEIGHT = 27.0   # inside the inner ring (r 24.5)
HEAD_THICK, HEAD_OVERHANG = 3.4, 1.6

d, bounds = mkmark.glyph_path(sys.argv[1], height=GLYPH_HEIGHT, box=(54, 55))
head = mkmark.headline(bounds, thick=HEAD_THICK, overhang=HEAD_OVERHANG)
x0, y0, x1, y1 = bounds

grad = f'''        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="{x0:.1f}" android:startY="{y0 - 2:.1f}" android:endX="{x1:.1f}" android:endY="{y1:.1f}">
                <item android:offset="0" android:color="#FFF3D58F" />
                <item android:offset="0.55" android:color="#FFD9A84E" />
                <item android:offset="1" android:color="#FF9A6B2A" />
            </gradient>
        </aapt:attr>'''

print(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Svan mark: a modern श (sha, as in श्रेष्ठम्) with a continuous brass headline,
     inside a brass yantra ring with nine radial marks. Generated by tools/brand/make_icon.py
     from Mukta Bold (SIL OFL 1.1). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#00000000"
        android:strokeColor="#D9A84E"
        android:strokeWidth="1.8"
        android:pathData="M54,25 A29,29 0 1,1 53.99,25 Z" />
    <path
        android:fillColor="#00000000"
        android:strokeColor="#9A6B2A"
        android:strokeWidth="0.9"
        android:pathData="M54,29.5 A24.5,24.5 0 1,1 53.99,29.5 Z" />
    <path
        android:fillColor="#00000000"
        android:strokeColor="#9A6B2A"
        android:strokeWidth="1"
        android:strokeLineCap="round"
        android:pathData="{mkmark.ring_marks()}" />
    <path android:pathData="{d}">
{grad}
    </path>
    <path android:pathData="{head}">
{grad}
    </path>
</vector>''')
